name: Integration tests

on:
  push:
    branches:
      - "*"
      - "!sapling-pr-archive-*"

jobs:
  test_integration_linux_x86_64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y gcc

      - name: Fetch Buck2
        uses: zadlg/buck2-github-composite-action@v2

      - name: Initialize an empty buck2 project
        run: |
          mkdir example/ && cd example
          buck2 init --git
          mkdir rules_openssl

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: example/rules_openssl

      - name: Create the `.buckconfig` file
        working-directory: example/
        run: |
          mv rules_openssl/.buckconfig .
          sed -i 's/rules_openssl = ./rules_openssl = rules_openssl/g' .buckconfig
          touch .buckroot

      - name: Import `openssl_archive` symbol in main BUCK file.
        working-directory: example/
        run: |
          echo -ne 'load("@rules_openssl//openssl:rules.bzl", "openssl_archive")' > BUCK

      - name: Compile OpenSSL
        working-directory: example/
        run: buck2 build -- @rules_openssl//...
